
function getList(){
	var array = new Array;
	array.push('Superman'); 
	array.push('Spider-gwen'); 
	array.push('Spiderman'); 
	array.push('Monty Python'); 
	array.push('Wonder Woman'); 
	array.push('Nightwing'); 
	array.push('Red Hood'); 
	array.push('Robin'); 
	array.push('Batman'); 
	array.push('Winter Soldier --- Bucky'); 
	array.push('Deadpool');
	array.push('Pikachu');  
	array.push('Detective Pikachu'); 
	array.push('Deadpool variant --- like pikapool or bob ross-pool', ); 
	array.push('Daredevil'); 
	array.push('Ariel --- Disney princesses'); 
	array.push('Repunzel --- Disney princesses'); 
	array.push('Jasmine --- Disney princesses'); 
	array.push('Tiana --- Disney princesses'); 
	array.push('Cinderella --- Disney princesses'); 
	array.push('Snow White --- Disney princesses'); 
	array.push('Captain America'); 
	array.push('Disney --- basically a free space'); 
	array.push('Mario --- or Luigi'); 
	array.push('Mariocart --- Any character'); 
	array.push('Harry potter --- anyone from'); 
	array.push('Furry --- fursuits are great'); 
	array.push('Mashup --- two characters combined'); 
	array.push('Genderbend --- the character presenting as a different gender'); 
	array.push('Khaleesi'); 
	array.push('??? Armor --- You don\'t know what it is, but it\'s cool'); 
	array.push('The Doctor --- Who?'); 
	array.push('Boku no Hero Academia --- Any character'); 
	array.push('Naruto --- Any character');
	array.push('Leia --- Star Wars');
	array.push('Rey --- Star Wars');
	array.push('Darth Vader --- Star Wars');
	array.push('Han Solo --- Star Wars');
	array.push('Firefly --- Any character');
	array.push('Kingdom Hearts --- Any character');
	array.push('Honey, hand me a towel --- Any character with a towel');
	array.push('Give me a sign --- holding a sign');
	array.push('Give me a hand --- holding a prop');
	array.push('Look ma, no hands! --- costume uses both hands');
	array.push('Where are my pants?? --- costume shows lots of skin');
	array.push('I hate myself --- Wearing a wig');
	array.push('I hate myself x2 --- Wearing a wig & leather');
	array.push('Ow my feet --- person in uncomfortable shoes');
	array.push('Oh that\'s new --- movie/game/tv show from the last 6 months');
	array.push('Legend of Zelda --- Any character');
	array.push('Final Fantasy --- Any character');
	return array;
}
