
function getList(){
	var array = new Array;
	array.push('"At Last"');
	array.push('"Baby Got Back --- or Anaconda"');
	array.push('"Before He Cheats"');
	array.push('"Black Velvet"');
	array.push('"Creep"');
	array.push('"Dragula"');
	array.push('"Friends in Low Places"');
	array.push('"I Touch Myself"');
	array.push('"I Will Survive"');
	array.push('"Live" version');
	array.push('"Livin\' on a Prayer"');
	array.push('"Santeria"');
	array.push('"Summer Nights"');
	array.push('"Sweet Caroline"');
	array.push('"Tainted Love"');
	array.push('"These Boots are Made for Walkin\'"');
	array.push('"Total Eclipse of the Heart"');
	array.push('"Wanted Dead or Alive"');
	array.push('3+ girls --- Betcha they\'re not harmonizing, either.');
	array.push('60s rock');
	array.push('70s rock');
	array.push('80s chick rock --- Excludes Madonna. That\'s not rock.');
	array.push('Alanis Morissette');
	array.push('Am I in key? --- Song that starts a capella');
	array.push('Anti-love song --- "One More Minute," "Everything About You," etc.');
	array.push('B-52s');
	array.push('Band campy --- Someone plays an air instrument');
	array.push('Billy Joel --- Anything by');
	array.push('Bitch --- The word in a song');
	array.push('Bon Jovi');
	array.push('Breakup song --- It\'s hard to do.');
	array.push('Bueller? --- KJ calls up someone who\'s left for the night');
	array.push('Butt Rock --- Didn\'t we burn all those albums yet?');
	array.push('Celine Dion');
	array.push('Dead air --- Start of a song delayed while singer on stage');
	array.push('Dedication --- "I\'d like to dedicate this song to my gerbil, Digger."');
	array.push('Deliberate change of lyrics --- Clever, or illiterate?');
	array.push('Disco');
	array.push('Do I have to? --- Obviously reluctant duet participant');
	array.push('Doin\' Great! --- Someone butchers a song you HATE');
	array.push('Drink in hand --- While singing');
	array.push('Drunk --- Too drunk to sing');
	array.push('Duets --- Written as one, that is');
	array.push('Elton John');
	array.push('Elvis Presley');
	array.push('Female Empowerment Song');
	array.push('Fresh air --- KJ calls up someone who\'s outside talking/smoking');
	array.push('fuck --- The word in a song');
	array.push('Gay anthems --- Not that the singer knows it is ...');
	array.push('Gender switch F2M --- Woman sings song made popular by a man');
	array.push('Gender switch M2F --- Man sings song made popular by a woman');
	array.push('Huh? --- Guy in cowboy hat sings something other than country');
	array.push('HUH? --- The overall sound is consistenly too loud');
	array.push('Imposter --- Someone sings a song for which you\'ve already entered a slip');
	array.push('Jimmy Buffett');
	array.push('Johnny Cash');
	array.push('Journey');
	array.push('Joke Singer --- "Look at me, I\'m employing defense mechanisms!"');
	array.push('Just the Chorus, please --- Singer doesn\'t know how the verses go');
	array.push('KJ Cliche --- "Put your hands together for ..."');
	array.push('Love song');
	array.push('Madonna');
	array.push('Make it stop! --- Someone butchers a song you love');
	array.push('Mariah Carey');
	array.push('Movie theme song');
	array.push('New Country, Female --- Rimes, Shania, Gretchen, etc.');
	array.push('New Country, Male --- Garth, Toby, etc.');
	array.push('No roofies this time, please --- Someone buys you a drink because of your singing');
	array.push('Notes. Use Them. --- Talking when they should be singing');
	array.push('Old Country, Female --- Patsy, June Carter, etc.');
	array.push('Old Country, Male --- Willie, Waylon, Strait, etc.');
	array.push('One-Hit Wonder');
	array.push('Our Traffic is Worse --- Song about a different city than yours');
	array.push('Ow! --- Mic Feedback');
	array.push('Pardon Me --- Someone asks to "borrow" your songbook');
	array.push('Peacocking --- Singer walks into the crowd');
	array.push('Puff --- Someone lights up a smoke right after they sing');
	array.push('Pulp Fiction soundtrack');
	array.push('Queen --- The band, not the lifestyle');
	array.push('Red Hot Chili Peppers');
	array.push('R.E.M.');
	array.push('Rocky Horror soundtrack');
	array.push('See ya --- Someone leaves for the night right after they sing');
	array.push('Shouting! --- Please turn down the mic!');
	array.push('Show Tunes --- From a play');
	array.push('Shy --- Too embarrassed to sing');
	array.push('Simon and Garfunkel you\'re not --- Failed attempts to harmonize');
	array.push('sing sing wait --- Song has a long instrumental ending ("Hotel California")');
	array.push('sing wait sing --- Song has a long instrumental break ("One Bouron, One Scotch, One Beer")');
	array.push('Sing yap sing --- Song has a spoken part between singing ("You Never Even ...")');
	array.push('Sing-along --- More than half the place sings a part.');
	array.push('Slow Ballad Ruins Mood --- The place is on fire! ... then someone turns on the sprinklers.');
	array.push('Song mentions specific body part');
	array.push('Song on Rock Band --- Cheater');
	array.push('Songs about dances --- Macarena, The Twist, etc.');
	array.push('The Beatles');
	array.push('The Cure');
	array.push('The pain! --- Song is obviously out of singer\'s range');
	array.push('U2');
	array.push('Uh, thanks? --- Someone way too drunk compliments your singing');
	array.push('Um, hello? --- KJ goes outside during a song');
	array.push('Unsolicited back-up dancers --- On the stage.');
	array.push('VIRGIN --- Someone sings karaoke for the first time');
	array.push('wait sing sing --- Song has a long instrumental intro ("Just Like Heaven", "One Night in Bangkok")');
	array.push('We are experiencing ... --- Technical difficulties');
	array.push('We\'re waitin\' here! --- Song over 7 minutes');
	array.push('What the hell? --- Song nobody at your table has heard of');
	array.push('WHAT? --- Someone tries to talk on their cell from their chair');
	array.push('When you gotta go ... --- KJ calls up someone who\'s in the restroom');
	array.push('Where\'s my drink? --- Bartender or waitperson sings');
	array.push('White Guy Does Rap/Hip-Hop --- You are not that cool.');
	array.push('Whitney Houston');
	array.push('Whoa! --- Someone has a much better voice than your tablemates were expecting');
	array.push('Woo! --- Three or more people at a table "woo!"');
	array.push('Yap sing sing --- Song has a spoken introduction ("Fuck her Gently")');
	array.push('Yes! Yes! --- Song alludes to orgasm');

	return array;
}