
function getList(){
	var array = new Array;
	array.push('Superman'); 
	array.push('Spider Gwen'); 
	array.push('Spider-man'); 
	array.push('Spider guy --- Spider-man variant'); 
	array.push('Monty Python --- Any character'); 
	array.push('Wonder Woman'); 
	array.push('Nightwing --- Dick is all grown up'); 
	array.push('Red Hood'); 
	array.push('Robin --- or any of Batman\'s kids'); 
	array.push('Batman'); 
	array.push('Winter Soldier --- Bucky'); 
	array.push('Deadpool');
	array.push('Pikachu');  
	array.push('Pokemon --- anything NOT a pikachu');  
	array.push('Pokemon trainer --- or Team Rocket');  
	array.push('Detective Pikachu'); 
	array.push('Deadpool variant --- like pikapool or bob ross-pool', ); 
	array.push('Daredevil'); 
	array.push('Ariel --- Disney princess'); 
	array.push('Repunzel --- Disney princess'); 
	array.push('Jasmine --- Disney princesses'); 
	array.push('Cinderella --- Disney princess'); 
	array.push('Captain America'); 
	array.push('Disney Princess --- Any of them'); 
	array.push('Mario --- or Luigi'); 
	array.push('Mariocart --- Any character'); 
	array.push('Harry potter --- anyone from'); 
	array.push('Furry --- fursuits are great'); 
	array.push('Mashup --- two characters combined'); 
	array.push('Genderbend --- the character presenting as a different gender'); 
	array.push('Khaleesi --- Game of Thrones'); 
	array.push('Game of Thrones --- Any character'); 
	array.push('??? Armor --- You don\'t know what it is, but it\'s cool'); 
	array.push('The Doctor --- Who?'); 
	array.push('Boku no Hero Academia --- Any character'); 
	array.push('Naruto --- Any character');
	array.push('Leia --- Star Wars');
	array.push('Rey --- Star Wars');
	array.push('Darth Vader --- Star Wars');
	array.push('Han Solo --- Star Wars');
	array.push('Stormtrooper --- Star Wars'); 
	array.push('Firefly --- Any character');
	array.push('Kingdom Hearts --- Any character');
	array.push('Honey, hand me a towel --- Any character with a towel');
	array.push('Give me a sign --- holding a sign');
	array.push('Give me a hand --- holding a prop');
	array.push('Look ma, no hands! --- costume uses both hands');
	array.push('Where are my pants?? --- costume shows lots of skin');
	array.push('I hate myself --- Wearing a wig');
	array.push('I hate myself x2 --- Wearing a wig & leather --- or a long coat');
	array.push('Ow my feet --- in uncomfortable shoes');
	array.push('Oh, that\'s new --- movie/game/tv show from the last 6 months');
	array.push('Legend of Zelda --- Any character');
	array.push('Final Fantasy --- Any character');
	array.push('Iron Man --- Full armor');
	array.push('Captain Marvel');
	array.push('Doctor Strange'); 
	array.push('Marvel --- Any character'); 
	array.push('No capes!! --- someone with a cape');   
	array.push('Mortal Kombat --- Any character'); 
	array.push('Sports Anime --- Someone with a numbered jersey'); 
	array.push('Spot the protagonist --- super crazy anime hair'); 
	array.push('I\'m with them --- one person in a group not in cosplay'); 
	array.push('I know him! --- spot a famous person'); 
	array.push('Wait wait don\'t tell me --- You know it, it\'s on the tip of your tongue...'); 
	array.push('Gold Star --- last-minute cosplay'); 
	array.push('Wolverine --- Xmen'); 
	array.push('Cosplaying while black --- hell yeah'); 
	array.push('Wheelchair user --- in cosplay'); 
	array.push('Hold my beer --- I could make that'); 
	array.push('That\'s lit --- light-up costume'); 
	array.push('Can I pet you? --- a textured costume'); 
	array.push('Alter-Ego --- The non-costumed version of a superhero'); 
	return array;
}
